### ISSUE TITLE
raise exception on fedora 34

### ISSUE THREAD

**Issue by x2c3z4** [earlephilhower/ezfio#54]
```
# ./ezfio.py -d /dev/sdc -u 1 --yes
***************************************************************************************************
ezFio test parameters:

               Drive: /dev/sdc
               Model: Linux scsi_debug 0190
              Serial: 10000
       AvailCapacity: 2 GiB
      TestedCapacity: 0 GiB
        TestedOffset: 0 GiB
                 CPU: AMD Ryzen 9 3950X 16-Core Processor
               Cores: 28
           Frequency: 3500
         FIO Version: fio-3.25


Test Description                                                        BW(MB/s)      IOPS  Lat(us)
----------------------------------------------------------------------- -------- --------- --------

---Sequential Preconditioning---
Sequential Preconditioning Pass 1                                                 00:00:00
FIO Error!
fio /tmp/tmp23y08oi8 --output-format=json+
STDOUT:

STDERR:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ezfio/./ezfio.py", line 1120, in JobWrapper
    val = o['cmdline'](o)
  File "/root/ezfio/./ezfio.py", line 1007, in <lambda>
    lambda o: {SequentialConditioning()})
  File "/root/ezfio/./ezfio.py", line 528, in SequentialConditioning
    raise FIOError(" ".join(cmdline), code, err, out)
__main__.FIOError
Sequential Preconditioning Pass 1                                          ERROR     ERROR    ERROR
ERROR DETECTED, ABORTING TEST RUN.

**Comment by earlephilhower** [comment]
>       AvailCapacity: 2 GiB
>      TestedCapacity: 0 GiB

Your drive seems to be 2GB??  Is this correct?  It's trying to do a test of size 0-bytes which is going to crap out either in fio or in the python when it hits a div-by-0 or equivalent.

I think testing on a normal sized drive might be all that's needed.  Can you re-run with a normal-sized volume?

**Comment by x2c3z4** [comment]
I use scsi_debug scsi device like this:
```
modprobe scsi_debug dev_size_mb=2048
```
This is a block device that is compatible with SCSI.

**Comment by earlephilhower** [comment]
That may be, but 2GB is not enough to run the test.  Use at least 10GB.

However `ezfio` is intended to test real SSDs or HDDs, or at least ones of normal sizes (1-30TB) so any results you get on a 10GB volume will not be useful or interesting...

**Comment by x2c3z4** [comment]
OK, Thanks.
